import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";

const RanuaTrials = localFont({
  src: "../public/fonts/RanuaTrials-Light.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RanuaTrials.className}  antialiased`}>
        <Header />

        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
